# Generated by Django 4.1.4 on 2022-12-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_address_alter_branch_name_and_more'),
        ('sales', '0002_remove_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch'),
        ),
    ]
