# Generated by Django 4.1.4 on 2022-12-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_address_alter_branch_name_and_more'),
        ('cars', '0010_alter_car_branch'),
        ('sales', '0003_sale_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car'),
        ),
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch'),
        ),
    ]
