# Generated by Django 4.1.4 on 2022-12-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('salary', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
