# Generated by Django 4.1.4 on 2022-12-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manager',
            table='managers',
        ),
    ]
