# Generated by Django 4.1.4 on 2022-12-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('model', models.CharField(max_length=250)),
                ('year', models.DateField(auto_now_add=True)),
                ('color', models.CharField(max_length=50)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
