# Generated by Django 4.1.4 on 2022-12-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_image_alter_car_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
    ]
