# Generated by Django 4.1.4 on 2022-12-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='categories',
            new_name='category',
        ),
    ]
