# Generated by Django 4.1.4 on 2022-12-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('cars', '0007_rename_categories_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch'),
        ),
    ]
