# Generated by Django 4.1.4 on 2023-01-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
