# Generated by Django 4.1.4 on 2022-12-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='employee',
        ),
    ]
