# Generated by Django 4.1.4 on 2022-12-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('salary', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('job', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sections.section')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
