# Generated by Django 4.1.4 on 2022-12-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cars',
        ),
    ]
